### ISSUE TITLE
Not able to access custom SQL image locally and remotely

### ISSUE THREAD

**Issue by eliassal** [dbafromthecold/examplesqldockerfiles#1]
Hi Andrew, I followed your session on the vistual group "sql and containers", I must say it is very usefull.
I followed instructions, created the custom image, I issued the command 
docker run -d -p 15777:1433 --name mycustomsqlimage testimage

A container is created and it is up and running, checked with docker ps, I can see
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS                     NAMES
47b7a5fcf5ba        testimage                   "cmd /S /C 'powers..."   15 minutes ago      Up 14 minutes       0.0.0.0:15777->1433/tcp   mycustomsqlimage

I tried to connect locally without success, I used
containerHost:15777
containerIP:15777
localhost:15777
No way, I am always getting "Network related issue.......error 53...."
I thought it might be related to firewall, I disabled the firewall but it did not help.

Thanks in advance for your help.

By the way, why the video at http://www.pass.org/Learning/Recordings/Listing.aspx?vRecording=1812&category=virtual cann't be watched in full screen mode?

**Comment by dbafromthecold** [comment]
Sorry, I am only seeing this now. To connect use

containerhost,15777

(comma instead of colon)
